export * from "./types";
export {
  openTestudoDatasetProvider,
  type OpenTestudoDatasetProviderOptions,
  type TestudoCatalogEntry,
  type TestudoDatasetDescriptor,
  type TestudoDatasetFormat,
  type TestudoDatasetMetadata,
  type TestudoDatasetProvider,
  type TestudoDatasetQuery,
  type TestudoDatasetQueryResult,
  type TestudoDatasetSource,
  type TestudoDuckDbConnection,
  type TestudoDuckDbRuntime,
  type TestudoFilterOperator,
  type TestudoProviderLimits,
  type TestudoQueryFilter,
  type TestudoScenarioMetadata,
  type TestudoSqliteDatabase,
  type TestudoSqliteRuntime,
} from "./plugins/testudo-dataset-provider";
export { PluginManager } from "./plugin-manager";
export {
  PATH_ANALYSIS_PLUGIN_ID,
  closePathAnalysisPanel,
  getPathAnalysisSnapshot,
  isPathAnalysisPanelVisible,
  maplibrePathAnalysisPlugin,
  openPathAnalysisPanel,
  reattachPathAnalysis,
  setPathAnalysisManifestUrl,
  setPathAnalysisSettings,
  clearPathAnalysisSelection,
  removePathAnalysisSection,
  loadLocalPathAnalysisFolder,
  subscribePathAnalysis,
  subscribePathAnalysisPanel,
  type PathAnalysisSettings,
  type PathAnalysisSnapshot,
} from "./plugins/maplibre-path-analysis";
export { PATH_METRICS, PATH_RAMPS, pathColorRgb, pathElevation, type PathMetric } from "./plugins/path-analysis-ramps";
export { maplibreScenarioComparisonPlugin, SCENARIO_COMPARISON_PLUGIN_ID, SCENARIO_COMPARISON_CONTINUOUS_RAMPS, openScenarioComparisonPanel, closeScenarioComparisonPanel, isScenarioComparisonPanelVisible, subscribeScenarioComparison, getScenarioComparisonSnapshot, getScenarioComparisonStatus, subscribeScenarioComparisonStatus, setScenarioComparisonSettings, reattachScenarioComparison, stepScenarioComparisonInterval, toggleScenarioComparisonIntervalPlaying, setScenarioComparisonManifestUrl, canLoadLocalScenarioComparisonPackage, loadLocalScenarioComparisonFolder, type ScenarioComparisonSettings, type ScenarioComparisonStatus } from "./plugins/maplibre-scenario-comparison";
export { buildScenarioComparisonRows, type ComparisonInput, type ComparisonRow } from "./plugins/scenario-comparison-data";
export { parseComparisonRamps, comparisonCategoricalRamp, type ComparisonMetric, type CategoricalRamp } from "./plugins/comparison-ramps";
export {
  loadPathAnalysis,
  parsePathAnalysisManifest,
  canLoadLocalPathAnalysisPackage,
  createPathAnalysisDirectorySource,
  readLocalPathAnalysisManifestJson,
  type PathAnalysisManifest,
  type PathMatch,
  type PathAnalysisSummary,
} from "./plugins/path-analysis-data";
export {
  registerRightPanel,
  unregisterRightPanel,
  openRightPanel,
  collapseRightPanel,
  closeRightPanel,
  getActiveRightPanel,
  setActiveRightPanelDock,
  moveActiveRightPanelDock,
  getActiveRightPanelDock,
  RIGHT_PANEL_DOCKS,
  isRightPanelCollapsed,
  isRightPanelVisible,
  getRightPanel,
  listRightPanels,
  getRightPanelSnapshot,
  subscribeRightPanels,
  type RightPanelSnapshot,
  type RightPanelDock,
} from "./right-panel-registry";
export {
  registerToolbarMenu,
  unregisterToolbarMenu,
  listToolbarMenus,
  getToolbarMenusSnapshot,
  subscribeToolbarMenus,
  type ToolbarMenusSnapshot,
  type ToolbarMenuEntry,
} from "./toolbar-menu-registry";
export {
  registerFloatingPanel,
  unregisterFloatingPanel,
  openFloatingPanel,
  closeFloatingPanel,
  focusFloatingPanel,
  isFloatingPanelOpen,
  getOpenFloatingPanels,
  getFloatingPanel,
  getFloatingPanelsSnapshot,
  subscribeFloatingPanels,
  type FloatingPanelsSnapshot,
} from "./floating-panel-registry";
// Public so hosts and plugins that ship their own panel-like registries can
// reuse the title-resolve-or-fallback + per-id warning-dedup behavior instead
// of re-implementing (and drifting from) it.
export { PanelTitleResolver } from "./panel-title";
export { maplibreLayerControlPlugin } from "./plugins/layer-control";
export { osmBasemapPlugin } from "./plugins/osm-basemap";
export { cartoLightPlugin } from "./plugins/carto-light";
export {
  maplibreBasemapControlPlugin,
  BASEMAP_CONTROL_PLUGIN_ID,
  getActiveBasemapControl,
  setBasemapControlLabels,
  type BasemapControlLabels,
} from "./plugins/maplibre-basemap-control";
export {
  addArcGISLayer,
  ARCGIS_FEATURE_SOURCE_KIND,
  ARCGIS_IMAGE_SERVICE_SOURCE_KIND,
  ARCGIS_LAYER_TYPES,
  ARCGIS_MAP_SERVICE_SOURCE_KIND,
  parseArcGISLayerType,
  refreshArcGISFeatureLayer,
  reloadArcGISViewportLayer,
  restoreArcGISViewportLayers,
  type ArcGISLayerOptions,
  type ArcGISLayerType,
  type ArcGISSourceType,
} from "./plugins/arcgis-layer";
export {
  addCogRasterLayer,
  closeBookmarkPanel,
  closeColorbarPanel,
  closeHtmlPanel,
  closeLegendPanel,
  closeMaplibreComponentControls,
  closeMeasurePanel,
  closeMinimapPanel,
  closePrintPanel,
  closeSearchPlacesPanel,
  closeSpinGlobePanel,
  closeViewStatePanel,
  isBookmarkPanelVisible,
  isColorbarPanelVisible,
  isHtmlPanelVisible,
  isLegendPanelVisible,
  isMeasurePanelVisible,
  isMinimapPanelVisible,
  isPrintPanelVisible,
  isSearchPlacesPanelVisible,
  isSpinGlobePanelVisible,
  isViewStatePanelVisible,
  COMPONENTS_PLUGIN_ID,
  maplibreComponentsPlugin,
  applyStacSearchLayerOrder,
  openBookmarkPanel,
  openFlatGeobufAddVectorLayerPanel,
  openColorbarPanel,
  openHtmlPanel,
  openLegendPanel,
  openLegendPanelWithItems,
  LIDAR_SOURCE_KIND,
  openLidarLayerPanel,
  restoreLidarLayers,
  openMeasurePanel,
  openMinimapPanel,
  openPMTilesLayerPanel,
  openPrintPanel,
  openSearchPlacesPanel,
  openSpinGlobePanel,
  openSplattingLayerPanel,
  openStacSearchLayerPanel,
  openViewStatePanel,
  openZarrLayerPanel,
  addCloudNetcdfLayer,
  type CloudNetcdfLayerOptions,
  addZarrRasterLayer,
  queryZarrLayer,
  setZarrLayerSelector,
  setZarrLocalStoreProvider,
  type ZarrRasterLayerOptions,
  type ZarrReadableStore,
  type ZarrTimeAttributesReader,
  setBookmarkLabels,
  setViewStateLabels,
  subscribeBookmarkPanel,
  subscribeColorbarPanel,
  subscribeHtmlPanel,
  subscribeLegendPanel,
  subscribeMeasurePanel,
  subscribeMinimapPanel,
  subscribePrintPanel,
  subscribeSearchPlacesPanel,
  subscribeSpinGlobePanel,
  subscribeViewStatePanel,
  type CogRasterLayerOptions,
} from "./plugins/maplibre-components";
export {
  KerchunkReferenceStore,
  loadKerchunkReference,
  listKerchunkVariables,
  normalizeKerchunkReference,
  type KerchunkRefs,
  type KerchunkVariable,
} from "./plugins/kerchunk-reference-store";
export {
  ZarrDirectoryStore,
  createDirectoryZarrMetadataReader,
  localZarrStoreUrl,
  normalizeZarrKey,
  type ZarrDirectoryReader,
  type ZarrMetadataReader,
} from "./plugins/zarr-directory-store";
export {
  openLocalNetcdf,
  openRemoteNetcdf,
  buildInlineZarrRefs,
  buildInlineZarrStore,
  composeColormappedImage,
  composeRgbImage,
  gridBounds,
  gridPixelAt,
  gridValueAt,
  percentileClim,
  type ColormapComposition,
  type RgbComposition,
  type LocalNetcdfAxis,
  type GridPixel,
  type LocalNetcdfGrid,
  type LocalNetcdfProfile,
  type LocalNetcdfProfileOptions,
  type LocalNetcdfColormappedImage,
  type LocalNetcdfFile,
  type LocalNetcdfImage,
  type LocalNetcdfVariable,
  type LocalNetcdfLayerRefs,
  type LocalNetcdfRgbImage,
  type LocalNetcdfRgbOptions,
  type LocalNetcdfWindow,
  type InlineZarrGrid,
} from "./plugins/local-netcdf";
export {
  closeDuckDBLayerPanel,
  getDuckDBFeatureBounds,
  getDuckDBLayerRows,
  identifyDuckDBLayerAtPoint,
  openDuckDBLayerPanel,
  setDuckDBSelectedFeature,
  updateDuckDBLayerRows,
  type DuckDBAttributeRow,
  type DuckDBIdentifyResult,
} from "./plugins/maplibre-duckdb";
export {
  queryOvertureFeatures,
  overtureFeatureMatchesFilter,
  overtureTilesForBBox,
} from "./plugins/overture-query";
export {
  closePlanetaryComputerPanel,
  openPlanetaryComputerPanel,
  PLANETARY_COMPUTER_SOURCE_KIND,
  restorePlanetaryComputerLayers,
} from "./plugins/maplibre-planetary-computer";
export {
  closeEarthEnginePanel,
  isEarthEnginePanelVisible,
  openEarthEnginePanel,
  subscribeEarthEnginePanel,
  toggleEarthEnginePanel,
} from "./plugins/maplibre-earth-engine";
export {
  EARTH_ENGINE_UNAVAILABLE_MESSAGE,
  isEarthEngineAvailable,
} from "./plugins/earth-engine-auth";
export {
  closeThreeDTilesLayerPanel,
  openThreeDTilesLayerPanel,
  restoreThreeDTilesLayers,
  THREE_D_TILES_SOURCE_KIND,
} from "./plugins/maplibre-3d-tiles";
export { isRecoverableNonTiledRasterError } from "./plugins/non-tiled-raster-error";
export {
  addRasterToMap,
  prepareRasterControl,
  applyRasterLayerOrder,
  closeRasterLayerPanel,
  openRasterLayerPanel,
  restoreRasterLayers,
  setLocalRasterFileReader,
  setLocalRasterPicker,
  setNonTiledRasterHandler,
  setRasterPixelInspect,
  type LocalRasterFileReader,
  type LocalRasterPicker,
  type NonTiledRasterRequest,
  type PickedLocalRaster,
} from "./plugins/maplibre-raster";
export {
  RASTER_MAX_CLASSES,
  RASTER_MAX_STORED_CLASSES,
  RASTER_MIN_CLASSES,
  RASTER_MIN_CUSTOM_COLORS,
  type RasterBandStats,
  type RasterClassificationMethod,
  type RasterSymbology,
  clampRasterClassCount,
  computeRasterBreaks,
  defaultRasterSymbology,
  savedRasterSymbology,
} from "./plugins/raster-symbology";
export { RASTER_SOURCE_KIND, getRasterBandStats } from "./plugins/raster-symbology-texture";
export {
  disposeAllPaletteLegends,
  disposePaletteLegend,
  extractPaletteLegend,
  getPaletteLegend,
  type PaletteLegendEntry,
} from "./plugins/raster-palette";
export { colormapColors, normalizeRampColor, warmColormapColors } from "./plugins/colormap-colors";
export { setTerrainMeasureLabels } from "./plugins/terrain-measure";
export {
  closeVectorLayerPanel,
  getVectorLayerPropertyValues,
  materializeEmbeddableVectorLayers,
  openVectorLayerPanel,
  reloadVectorControlLayer,
  replayVectorControlLayerById,
  restoreVectorLayers,
  setKmlFileImportHandler,
  isKmlFileSelection,
  routeKmlFileSelection,
  type KmlFileImport,
  type KmlFileImportHandler,
} from "./plugins/maplibre-vector";
// The rest of the raster-layer-sync / vector-layer-sync internals stay
// unexported: the app drives the panels through the functions above, and the
// tests import the sync helpers from the module paths directly. These two are
// the exception — the Layer Library (issue #1520) has to recognize a
// control-painted vector layer to read its features before saving it, and to
// route a re-add back to restoreVectorLayers.
export { isEmbeddableLocalVectorLayer, VECTOR_SOURCE_KIND } from "./plugins/vector-layer-sync";
export {
  clearDirectionsWaypoints,
  type DirectionsRouteLegMetric,
  type DirectionsRouteMetrics,
  DIRECTIONS_PLUGIN_ID,
  getDirectionsRouteMetrics,
  getDirectionsWaypointCount,
  isDirectionsRemovalInFlight,
  isDirectionsRouteLoading,
  maplibreDirectionsPlugin,
  removeLastDirectionsWaypoint,
  restoreDirections,
  subscribeDirectionsState,
} from "./plugins/maplibre-directions";
export {
  REVERSE_GEOCODE_PLUGIN_ID,
  maplibreReverseGeocodePlugin,
  restoreReverseGeocode,
  setReverseGeocodeLabels,
  type ReverseGeocodeLabels,
} from "./plugins/maplibre-reverse-geocode";
export {
  DEFAULT_EFFECTS_SETTINGS,
  EFFECTS_PLUGIN_ID,
  type EffectsSettings,
  getEffectsSettings,
  HALO_EXTENT_MAX,
  HALO_EXTENT_MIN,
  HALO_OPACITY_MAX,
  HALO_OPACITY_MIN,
  maplibreEffectsPlugin,
  restoreEffects,
  setEffectsSettings,
} from "./plugins/maplibre-effects";
export {
  advanceSunClock,
  closeSunPanel,
  DEFAULT_SUN_SETTINGS,
  getSunSettings,
  getSunSettingsSnapshot,
  isSunPanelVisible,
  localDayStart,
  maplibreSunPlugin,
  normalizeSunSettings,
  openSunPanel,
  reattachSun,
  restoreSun,
  setSunSettings,
  SUN_PLUGIN_ID,
  SUN_SHADE_MAX,
  SUN_SHADE_MIN,
  SUN_SPEED_MAX,
  SUN_SPEED_MIN,
  type SunSettings,
  subsolarPoint,
  subscribeSunPanel,
  subscribeSunSettings,
  sunEquatorialPosition,
  sunPositionAt,
} from "./plugins/maplibre-sun";
export { DECK_VIZ_PLUGIN_ID, maplibreDeckGlVizPlugin } from "./plugins/maplibre-deckgl-viz";
export { restoreDeckViz } from "./plugins/deckgl-viz/overlay";
export { countAtlasDroppedDiagrams } from "./plugins/deckgl-viz/diagrams";
export { ensureMercatorProjection } from "./plugins/map-projection-utils";
export {
  DECK_VIZ_CATEGORY_LABELS,
  DEFAULT_DECK_VIZ_SCENEGRAPH,
  DEFAULT_DECK_VIZ_STYLE,
  getDeckVizLayerDef,
  listDeckVizLayerDefs,
  type DeckVizCategory,
  type DeckVizConfig,
  type DeckVizFieldMapping,
  type DeckVizFormat,
  type DeckVizInputKind,
  type DeckVizLayerDef,
  type DeckVizRole,
  type DeckVizScenegraphConfig,
  type DeckVizStyle,
  type DeckVizStyleControl,
} from "./plugins/deckgl-viz/registry";
export {
  createDeckVizStoreLayer,
  DECK_VIZ_SOURCE_KIND,
  isDeckVizLayer,
} from "./plugins/deckgl-viz/store-layer";
export { VIEWER_BLOCKED_PLUGIN_IDS } from "./viewer-plugins";
export {
  maplibreAnnotationsPlugin,
  ANNOTATIONS_PLUGIN_ID,
  ANNOTATIONS_SOURCE_KIND,
  setAnnotationLabels,
  type AnnotationLabels,
} from "./plugins/maplibre-annotations";
export { maplibreEnviroAtlasPlugin } from "./plugins/maplibre-enviroatlas";
export { maplibreEsriWaybackPlugin } from "./plugins/maplibre-esri-wayback";
export { maplibreFemaWmsPlugin } from "./plugins/maplibre-fema-wms";
export {
  maplibreGeoEditorPlugin,
  GEO_EDITOR_PLUGIN_ID,
  canEditLayerGeometry,
  SKETCHES_SOURCE_KIND,
  startLayerGeometryEdit,
  endLayerGeometryEdit,
  getGeometryEditTargetLayerId,
  subscribeGeometryEdit,
  isGeoEditorAvailableForImport,
  getGeoEditorFeatureCount,
  hasViewImportBaseline,
  loadViewFeaturesIntoEditor,
  buildEditorSaveCollection,
} from "./plugins/maplibre-geo-editor";
export {
  listViewVectorLayers,
  resolveStoreLayerViewSource,
  queryViewLayerFeatures,
  VIEW_IMPORT_ID_PROPERTY,
  VIEW_IMPORT_CHANGE_PROPERTY,
  type ViewVectorLayer,
  type ViewImportMap,
  type ViewImportExport,
  type ViewImportChangeCounts,
} from "./plugins/geo-editor-view-import";
export { maplibreGeoAgentPlugin, GEOAGENT_PLUGIN_ID } from "./plugins/maplibre-geoagent";
export { maplibreUsgsLidarPlugin } from "./plugins/maplibre-usgs-lidar";
export { maplibreNasaEarthdataPlugin } from "./plugins/maplibre-nasa-earthdata";
export {
  DEFAULT_EARTHDATA_GIS_LABELS,
  EARTHDATA_GIS_PLUGIN_ID,
  maplibreEarthdataGisPlugin,
  setEarthdataCogSaver,
  setEarthdataGisLabels,
  type EarthdataCogSaver,
  type EarthdataGisLabels,
} from "./plugins/maplibre-earthdata-gis";
// The catalog client's helpers (buildSearchUrl, parseSearchResponse, …) are
// deliberately not re-exported here: those names are already taken by the
// OpenAerialMap client below. Import them from the module path instead.
export {
  EARTHDATA_GIS_PORTAL_URL,
  type EarthdataGisItem,
  type EarthdataGisSearchResult,
  type EarthdataServiceKind,
} from "./plugins/earthdata-gis-api";
export {
  DEFAULT_OPENAERIALMAP_LABELS,
  maplibreOpenAerialMapPlugin,
  OPENAERIALMAP_PLUGIN_ID,
  setOpenAerialMapLabels,
  type OpenAerialMapLabels,
} from "./plugins/maplibre-openaerialmap";
export {
  ARCGIS_HUB_PLUGIN_ID,
  DEFAULT_ARCGIS_HUB_LABELS,
  maplibreArcGisHubPlugin,
  setArcGisHubLabels,
  type ArcGisHubLabels,
} from "./plugins/maplibre-arcgis-hub";
export {
  ARCGIS_HUB_PAGE_URL,
  ARCGIS_HUB_PORTAL_URL,
  arcGisHubItemDataUrl,
  arcGisHubItemPageUrl,
  arcGisHubItemThumbnailUrl,
  buildArcGisHubSearchUrl,
  fetchFeatureServiceGeoJson,
  itemBounds as arcGisHubItemBounds,
  sanitizeArcGisHubSearchText,
  searchArcGisHub,
  type ArcGisHubItem,
  type ArcGisHubSearchResult,
} from "./plugins/arcgis-hub-api";
export {
  buildSearchUrl,
  buildTitilerTemplate,
  OAM_DEFAULT_ENDPOINT,
  parseSearchResponse,
  searchOpenAerialMap,
  type OamImage,
  type OamSearchResult,
  type OpenAerialMapSearchOptions,
} from "./plugins/openaerialmap-api";
export {
  maplibreStacCatalogsPlugin,
  setStacLabels,
  STAC_PLUGIN_ID,
  type StacLabels,
} from "./plugins/maplibre-stac";
export {
  connectStac,
  isVisualizableAsset,
  itemBbox,
  loadStacIndex,
  searchStacApi,
  searchStaticStac,
  STAC_INDEX_CATALOGS_URL,
  type StacAsset,
  type StacCollection,
  type StacConnection,
  type StacIndexCatalog,
  type StacItem,
  type StacNextPage,
  type StacSearchOptions,
  type StacSearchResult,
} from "./plugins/stac-api";
export {
  DEFAULT_SOURCE_COOP_LABELS,
  maplibreNaturalEarthPlugin,
  maplibreSourceCoopPlugin,
  NATURAL_EARTH_PLUGIN_ID,
  setSourceCoopLabels,
  SOURCE_COOP_PLUGIN_ID,
  type SourceCoopLabels,
  type SourceCoopPinnedProduct,
} from "./plugins/maplibre-source-coop";
export {
  DEFAULT_HUGGINGFACE_LABELS,
  HUGGINGFACE_PLUGIN_ID,
  maplibreHuggingFacePlugin,
  setHuggingFaceLabels,
  type HuggingFaceLabels,
} from "./plugins/maplibre-huggingface";
export {
  createGeoLensHostFetch,
  defaultGeoLensFetch,
  resetGeoLensFetch,
  setGeoLensFetch,
  type GeoLensFetch,
  type GeoLensHttpResponse,
} from "./plugins/geolens-api";
export {
  DEFAULT_GEOLENS_LABELS,
  DEFAULT_GEOLENS_FEATURE_LIMIT,
  GEOLENS_FEATURES_SOURCE_KIND,
  GEOLENS_PLUGIN_ID,
  GEOLENS_SAMPLE_SERVERS,
  maplibreGeoLensPlugin,
  normalizeGeoLensFeatureLimit,
  setGeoLensLabels,
  type GeoLensLabels,
  type GeoLensSampleServer,
} from "./plugins/maplibre-geolens";
export {
  buildListObjectsUrl,
  buildObjectUrl,
  classifyKey,
  fetchCatalog,
  filterProducts,
  formatBytes,
  isAddable,
  listProductObjects,
  parseFeed,
  parseListObjects,
  parseProduct,
  parseProductList,
  parseProductRef,
  productUrl,
  SOURCE_COOP_DATA_BASE,
  SOURCE_COOP_PROXY_ENDPOINT,
  synthesizeProduct,
  type SourceCoopFormat,
  type SourceCoopListing,
  type SourceCoopObject,
  type SourceCoopProduct,
} from "./plugins/source-coop-api";
export { maplibreNationalMapPlugin } from "./plugins/maplibre-national-map";
export { maplibreOvertureMapsPlugin } from "./plugins/maplibre-overture-maps";
export { maplibreStreetViewPlugin } from "./plugins/maplibre-streetview";
export {
  maplibreMapillaryPlugin,
  MAPILLARY_PLUGIN_ID,
  setMapillaryLabels,
  type MapillaryLabels,
} from "./plugins/maplibre-mapillary";
export {
  maplibreElevationProfilePlugin,
  ELEVATION_PROFILE_PLUGIN_ID,
} from "./plugins/elevation-profile";
export { maplibreSwipePlugin, SWIPE_PLUGIN_ID } from "./plugins/maplibre-swipe";
export {
  maplibreGraticulePlugin,
  GRATICULE_PLUGIN_ID,
  GRATICULE_LABEL_LAYER_ID,
  DEFAULT_GRATICULE_SETTINGS,
  DEFAULT_GRATICULE_LABELS,
  getGraticuleSettings,
  setGraticuleSettings,
  setGraticuleLabels,
  normalizeGraticuleSettings,
  type GraticuleSettings,
  type GraticuleLabels,
  type GraticuleLabelFormat,
  type GraticuleLabelEdges,
} from "./plugins/maplibre-graticule";
export {
  maplibreH3Plugin,
  H3_PLUGIN_ID,
  H3_VIEWPORT_CELL_LIMIT,
  DEFAULT_H3_GRID_SETTINGS,
  DEFAULT_H3_LABELS,
  getH3GridSettings,
  setH3GridSettings,
  setH3Labels,
  normalizeH3GridSettings,
  h3LabelMinZoom,
  h3ResolutionForZoom,
  h3CellFeature,
  h3GridForBounds,
  h3FixTransmeridianBoundary,
  type H3GridSettings,
  type H3Labels,
} from "./plugins/maplibre-h3";
export {
  maplibreS2Plugin,
  S2_PLUGIN_ID,
  MAX_S2_LEVEL,
  S2_VIEWPORT_CELL_LIMIT,
  DEFAULT_S2_GRID_SETTINGS,
  DEFAULT_S2_LABELS,
  getS2GridSettings,
  setS2GridSettings,
  setS2Labels,
  normalizeS2GridSettings,
  s2LabelMinZoom,
  s2LevelForZoom,
  s2CellFeature,
  s2GridForBounds,
  type S2GridSettings,
  type S2Labels,
} from "./plugins/maplibre-s2";
export { DGGS_PLUGIN_IDS } from "./plugins/dggs-group";
export {
  maplibreA5Plugin,
  A5_PLUGIN_ID,
  A5_VIEWPORT_CELL_LIMIT,
  DEFAULT_A5_GRID_SETTINGS,
  DEFAULT_A5_LABELS,
  getA5GridSettings,
  setA5GridSettings,
  setA5Labels,
  normalizeA5GridSettings,
  a5LabelMinZoom,
  a5ResolutionForZoom,
  a5CellFeature,
  a5GridForBounds,
  type A5GridSettings,
  type A5Labels,
} from "./plugins/maplibre-a5";
export {
  maplibreDggridPlugin,
  DGGRID_PLUGIN_ID,
  DGGRID_CONFIG,
  DGGRID_TOPOLOGIES,
  DGGRID_PROJECTIONS,
  DGGRID_APERTURES,
  MAX_DGGRID_RESOLUTION,
  DGGRID_VIEWPORT_CELL_LIMIT,
  DEFAULT_DGGRID_GRID_SETTINGS,
  DEFAULT_DGGRID_LABELS,
  getDggridGridSettings,
  setDggridGridSettings,
  setDggridLabels,
  normalizeDggridGridSettings,
  dggridLabelMinZoom,
  dggridResolutionForZoom,
  dggridCellFeature,
  dggridGridForBounds,
  loadDggrid,
  type DggridGridSettings,
  type DggridLabels,
  type DggridTopology,
  type DggridProjection,
  type DggridAperture,
} from "./plugins/maplibre-dggrid";
export {
  maplibreDggalPlugin,
  DGGAL_PLUGIN_ID,
  DGGAL_TYPES,
  DGGAL_TYPE_NAMES,
  DGGAL_VIEWPORT_CELL_LIMIT,
  DEFAULT_DGGAL_GRID_SETTINGS,
  DEFAULT_DGGAL_LABELS,
  getDggalGridSettings,
  setDggalGridSettings,
  setDggalLabels,
  normalizeDggalGridSettings,
  dggalLabelMinZoom,
  dggalResolutionForZoom,
  dggalZoneFeature,
  dggalParentZones,
  dggalGridForBounds,
  loadDggal,
  type DggalGridSettings,
  type DggalLabels,
  type DggalType,
  type DggalEngine,
  type DggalDggrs,
} from "./plugins/maplibre-dggal";
export {
  maplibreOlcPlugin,
  OLC_PLUGIN_ID,
  OLC_CODE_LENGTHS,
  OLC_VIEWPORT_CELL_LIMIT,
  MAX_OLC_CODE_LENGTH,
  DEFAULT_OLC_GRID_SETTINGS,
  DEFAULT_OLC_LABELS,
  getOlcGridSettings,
  setOlcGridSettings,
  setOlcLabels,
  normalizeOlcGridSettings,
  olcLabelMinZoom,
  olcResolutionForZoom,
  olcCellFeature,
  olcGridForBounds,
  olcParentCell,
  olcChildCount,
  olcNeighborCells,
  type OlcGridSettings,
  type OlcLabels,
  type OlcCodeLength,
} from "./plugins/maplibre-olc";
export {
  maplibreGeohashPlugin,
  GEOHASH_PLUGIN_ID,
  GEOHASH_VIEWPORT_CELL_LIMIT,
  GEOHASH_CHILDREN_PER_CELL,
  MIN_GEOHASH_PRECISION,
  MAX_GEOHASH_PRECISION,
  DEFAULT_GEOHASH_GRID_SETTINGS,
  DEFAULT_GEOHASH_LABELS,
  getGeohashGridSettings,
  setGeohashGridSettings,
  setGeohashLabels,
  normalizeGeohashGridSettings,
  geohashLabelMinZoom,
  geohashResolutionForZoom,
  geohashCellFeature,
  geohashGridForBounds,
  geohashParentCell,
  geohashNeighborCells,
  type GeohashGridSettings,
  type GeohashLabels,
} from "./plugins/maplibre-geohash";
export {
  maplibreTilecodePlugin,
  TILECODE_PLUGIN_ID,
  TILECODE_VIEWPORT_CELL_LIMIT,
  TILECODE_CHILDREN_PER_CELL,
  MIN_TILECODE_ZOOM,
  MAX_TILECODE_ZOOM,
  DEFAULT_TILECODE_GRID_SETTINGS,
  DEFAULT_TILECODE_LABELS,
  getTilecodeGridSettings,
  setTilecodeGridSettings,
  setTilecodeLabels,
  normalizeTilecodeGridSettings,
  tilecodeLabelMinZoom,
  tilecodeResolutionForZoom,
  tilecodeCellFeature,
  tilecodeGridForBounds,
  tilecodeParentCell,
  tilecodeNeighborCells,
  tileToTilecode,
  tilecodeToTile,
  tileToQuadkey,
  pointToTile,
  type Tile,
  type TilecodeGridSettings,
  type TilecodeLabels,
} from "./plugins/maplibre-tilecode";
export type { WeatherAnimationState, WeatherLayerController } from "./plugins/weather-layer";
export {
  useManifestUrlDraft,
  type UseManifestUrlDraftResult,
} from "./shared/useManifestUrlDraft";
export {
  useScenarioReplicationSelector,
  type ReplicationLike,
  type ScenarioLike,
  type UseScenarioReplicationSelectorArgs,
  type UseScenarioReplicationSelectorResult,
} from "./shared/useScenarioReplicationSelector";
export {
  deriveIntervalPlayback,
  stepInterval,
  toggleAggregateInterval,
  useIntervalPlayback,
  type IntervalPlaybackDerivation,
  type UseIntervalPlaybackArgs,
  type UseIntervalPlaybackResult,
} from "./shared/useIntervalPlayback";
export {
  formatSimClock,
  tickTimelineProps,
  useTickPlayback,
  type TickTimelineProps,
  type UseTickPlaybackArgs,
  type UseTickPlaybackResult,
} from "./shared/useTickPlayback";
export {
  heightSliderProps,
  useViewModeToggle,
  type HeightSliderProps,
  type UseViewModeToggleArgs,
  type UseViewModeToggleResult,
} from "./shared/useViewModeToggle";
export {
  maplibreCloudsPlugin,
  CLOUDS_PLUGIN_ID,
  getCloudsAnimationState,
  setCloudsFrame,
  toggleCloudsPlaying,
  subscribeClouds,
} from "./plugins/maplibre-clouds";
export {
  maplibrePrecipitationPlugin,
  PRECIPITATION_PLUGIN_ID,
  getPrecipitationAnimationState,
  setPrecipitationFrame,
  togglePrecipitationPlaying,
  subscribePrecipitation,
} from "./plugins/maplibre-precipitation";
export {
  maplibreTimeSliderPlugin,
  TIME_SLIDER_PLUGIN_ID,
  TIME_SLIDER_SOURCE_KIND,
  getActiveTimeSliderControl,
  getLayerTimeBinding,
  isTimeSliderIdle,
} from "./plugins/maplibre-time-slider";
export {
  DEFAULT_TIMELAPSE_LABELS,
  getActiveTimelapseControl,
  maplibreTimelapsePlugin,
  recordTimelapseCycle,
  setTimelapseLabels,
  setTimelapseVideoSaver,
  TIMELAPSE_PANEL_ID,
  TIMELAPSE_PLUGIN_ID,
  TIMELAPSE_SOURCE_KIND,
  timelapseStoreLayerId,
  TimelapseControl,
  TimelapseVideoUnsupportedError,
  type RecordTimelapseCycleOptions,
  type TimelapseLabels,
  type TimelapseRecording,
  type TimelapseVideoSaver,
} from "./plugins/maplibre-timelapse";
export {
  eoxS2CloudlessProvider,
  EOX_S2CLOUDLESS_PROVIDER_ID,
  getTimelapseProvider,
  listTimelapseProviders,
  MODIS_LANDCOVER_PROVIDER_ID,
  modisLandCoverProvider,
  NASA_GIBS_WELD_NDVI_PROVIDER_ID,
  NASA_GIBS_WELD_PROVIDER_ID,
  nasaGibsWeldNdviProvider,
  nasaGibsWeldProvider,
  registerTimelapseProvider,
  type TimelapseFrame,
  type TimelapseLegendItem,
  type TimelapseProvider,
} from "./plugins/timelapse-providers";
export {
  bandOptionsFromResults,
  downsampleSteps,
  getTimeSliderPixelSources,
  hasTimeSliderRasterStack,
  ordinalSteps,
  queryPixelTimeSeries,
  seriesToFeatureCollection,
  valueAtBand,
  type BandOption,
  type LabeledPixelTimeSeries,
  type PixelSeries,
  type PixelSeriesPoint,
  type PixelTimeSeriesOptions,
  type PixelTimeSeriesResult,
} from "./plugins/time-slider-pixel-series";
export {
  getTimeSliderSymbology,
  parseBandList,
  setTimeSliderSymbology,
  type TimeSliderSymbology,
  type TimeSliderSymbologyPatch,
} from "./plugins/time-slider-symbology";
export {
  getPixelIdentifiableSource,
  identifyTimeSliderPixel,
  isPixelIdentifiableSourceType,
  PixelOutsideCoverageError,
  type PixelIdentifiableSpec,
  type TimeSliderPixelIdentifyResult,
} from "./plugins/time-slider-pixel-identify";
export {
  buildTimeBinding,
  buildTimeBindingFromRecords,
  buildTimeFilter,
  detectTimeProperties,
  detectTimePropertiesFromRecords,
  formatTimeExtentInput,
  parseTimeValue,
  type BuildTimeBindingOptions,
  type TimeBinding,
  type TimeGranularity,
  type TimePropertyCandidate,
  type TimePropertyRecord,
  type TimeValueKind,
  type TimeWindow,
} from "./plugins/time-slider-binding";
export {
  buildSelectorTimeBinding,
  getTemporalLayerAdapter,
  getTemporalLayersVersion,
  isSelectorTimeBinding,
  nearestTimeIndex,
  registerTemporalLayer,
  subscribeTemporalLayers,
  toEpochMsAxis,
  unregisterTemporalLayer,
  type SelectorTimeBinding,
  type TemporalLayerAdapter,
} from "./plugins/temporal-layers";
export {
  decodeCfTimeValues,
  fetchZarrTimeAttributes,
  parseCfTimeUnits,
  pickTimeDimension,
  resolveZarrTimeAxis,
  type CfTimeUnits,
  type ZarrTimeAttributes,
  type ZarrTimeAxis,
} from "./plugins/zarr-time-axis";
export {
  isTileVectorLayer,
  resolveTileQueryTargets,
  sampleTileFeatureRecords,
  type TileQueryTarget,
  type TileSampleMap,
  type TileSampleStyle,
} from "./plugins/time-slider-tile-sample";
export { WEB_SERVICE_PLUGIN_IDS } from "./plugins/web-service-sync";
export {
  CKAN_PLUGIN_ID,
  SOCRATA_PLUGIN_ID,
  maplibreCkanPlugin,
  maplibreSocrataPlugin,
  setOpenDataCatalogLabels,
  type OpenDataCatalogLabels,
} from "./plugins/maplibre-open-data-catalogs";
export {
  DEFAULT_ROUTE_ANIMATION_SETTINGS,
  ROUTE_ANIM_SPEED_MAX,
  ROUTE_ANIM_SPEED_MIN,
  ROUTE_ANIMATION_PLUGIN_ID,
  ROUTE_FOLLOW_PITCH_MAX,
  ROUTE_FOLLOW_PITCH_MIN,
  ROUTE_FOLLOW_ZOOM_MAX,
  ROUTE_FOLLOW_ZOOM_MIN,
  ROUTE_MARKER_STYLES,
  ROUTE_VIDEO_FPS,
  ROUTE_VIDEO_MIME_CANDIDATES,
  RouteVideoUnsupportedError,
  closeRouteAnimationPanel,
  getRouteAnimationDurationSeconds,
  getRouteAnimationSettings,
  getRouteAnimationSnapshot,
  isRouteAnimationPanelVisible,
  isRouteVideoSupported,
  maplibreRouteAnimationPlugin,
  normalizeRouteAnimationSettings,
  openRouteAnimationPanel,
  pickRouteVideoMimeType,
  pickVideoMimeType,
  reattachRouteAnimation,
  recordRouteAnimation,
  restoreRouteAnimation,
  setRouteAnimationElevation,
  setRouteAnimationProgress,
  setRouteAnimationRoute,
  setRouteAnimationSettings,
  subscribeRouteAnimation,
  subscribeRouteAnimationPanel,
  toggleRouteAnimationPlaying,
  videoExtensionForMime,
  type RecordRouteAnimationOptions,
  type RouteAnimationRecording,
  type RouteAnimationSettings,
  type RouteElevationConfig,
  type RouteMarkerStyle,
} from "./plugins/maplibre-route-animation";
export {
  bearingBetween,
  flattenToLine,
  flattenToRoute,
  measureLine,
  pointAlongLine,
  sliceLineAtDistance,
  sliceRouteAtDistance,
  type PointOnLine,
  type RouteWithElevation,
} from "./plugins/route-animation-geometry";
export {
  canLoadLocalNetworkKpiPackage,
  closeNetworkKpiPanel,
  DEFAULT_NETWORK_KPI_SETTINGS,
  getNetworkKpiSettings,
  getNetworkKpiSnapshot,
  getNetworkKpiStatus,
  isNetworkKpiPanelVisible,
  loadLocalNetworkKpiFolder,
  maplibreNetworkKpiPlugin,
  NETWORK_KPI_MAX_HEIGHT_MAX,
  NETWORK_KPI_MAX_HEIGHT_MIN,
  NETWORK_KPI_OPACITY_MAX,
  NETWORK_KPI_OPACITY_MIN,
  NETWORK_KPI_PLUGIN_ID,
  normalizeNetworkKpiSettings,
  openNetworkKpiPanel,
  reattachNetworkKpi,
  restoreNetworkKpi,
  setNetworkKpiManifestUrl,
  setNetworkKpiScenario,
  setNetworkKpiReplication,
  setNetworkKpiSettings,
  stepNetworkKpiInterval,
  toggleNetworkKpiIntervalPlaying,
  subscribeNetworkKpi,
  subscribeNetworkKpiPanel,
  subscribeNetworkKpiStatus,
  type NetworkKpiSettings,
  type NetworkKpiStatus,
} from "./plugins/maplibre-network-kpi";
export {
  DEFAULT_MAX_HEIGHT_M,
  elevationByKpi,
  kpiColorRgb,
  kpiInterpolateExpression,
  kpiLegendStops,
  KPI_RAMPS,
  KPI_RANGES,
  LOD_ZOOM_THRESHOLD,
  NETWORK_KPI_METRICS,
  type KpiRamp,
  type NetworkKpiMetric,
} from "./plugins/network-kpi-ramps";
export {
  bufferLineToRing,
  buildLaneRows,
  buildSectionRows,
  type KpiPolygonRow,
} from "./plugins/network-kpi-geometry";
export {
  laneKey,
  parseNetworkKpiManifest,
  type KpiRow,
  type NetworkKpiGeometry,
  type NetworkKpiManifest,
  type NetworkKpiResults,
} from "./plugins/network-kpi-data";
export {
  EMISSIONS_H3_PLUGIN_ID, DEFAULT_EMISSIONS_H3_SETTINGS, maplibreEmissionsH3Plugin,
  EMISSIONS_H3_RESOLUTION_MIN, EMISSIONS_H3_RESOLUTION_MAX,
  openEmissionsH3Panel, closeEmissionsH3Panel, reattachEmissionsH3,
  isEmissionsH3PanelVisible, subscribeEmissionsH3Panel, getEmissionsH3Snapshot,
  subscribeEmissionsH3, getEmissionsH3Status, subscribeEmissionsH3Status,
  setEmissionsH3Settings, setEmissionsH3ManifestUrl, loadLocalEmissionsH3Folder, toggleEmissionsH3IntervalPlaying, stepEmissionsH3Interval, setEmissionsH3Scenario,
  aggregateEmissionsH3, type EmissionsH3Settings, type EmissionsH3Status,
} from "./plugins/maplibre-emissions-h3";
export { computeNoiseSource, energyWeightedDb } from "./plugins/emissions-h3-data";
export { EMISSIONS_H3_METRICS, EMISSIONS_H3_RAMPS, type EmissionsH3Metric } from "./plugins/emissions-h3-ramps";
export {
  advanceVehiclePlaybackTick,
  canLoadLocalVehiclePackage,
  closeVehiclePlaybackPanel,
  DEFAULT_VEHICLE_PLAYBACK_SETTINGS,
  loadLocalVehiclePlaybackFolder,
  setVehiclePlaybackScenario,
  getVehiclePlaybackSettings,
  getVehiclePlaybackSnapshot,
  getVehiclePlaybackStatus,
  isVehiclePlaybackPanelVisible,
  maplibreVehiclePlaybackPlugin,
  normalizeVehiclePlaybackSettings,
  openVehiclePlaybackPanel,
  reattachVehiclePlayback,
  restoreVehiclePlayback,
  setVehiclePlaybackManifestUrl,
  setVehiclePlaybackSettings,
  setVehiclePlaybackTick,
  subscribeVehiclePlayback,
  subscribeVehiclePlaybackPanel,
  subscribeVehiclePlaybackStatus,
  toggleVehiclePlaybackPlaying,
  VEHICLE_PLAYBACK_OPACITY_MAX,
  VEHICLE_PLAYBACK_OPACITY_MIN,
  VEHICLE_PLAYBACK_PLUGIN_ID,
  VEHICLE_PLAYBACK_SPEED_MAX,
  VEHICLE_PLAYBACK_SPEED_MIN,
  type VehicleNetworkView,
  type VehiclePlaybackSettings,
  type VehiclePlaybackStatus,
} from "./plugins/maplibre-vehicle-playback";
export {
  articulatedSegmentCount,
  articulatedVehicleFootprints,
  createDirectoryPackageSource,
  createHttpPackageSource,
  interpolateFrames,
  isArticulatedSample,
  listVehicleManifestScenarios,
  loadVehicleGeometry,
  loadVehiclePlayback,
  openLocalVehiclePackage,
  parseVehicleManifest,
  supportsLocalPackageFolders,
  vehicleFootprint,
  VehiclePlaybackData,
  type VehicleChunkEntry,
  type VehicleDirectoryHandle,
  type VehicleGeometryLayers,
  type VehicleGeometrySources,
  type VehicleHistoryEntry,
  type VehicleManifest,
  type VehicleManifestScenario,
  type VehiclePackageSource,
  type VehicleSample,
} from "./plugins/vehicle-playback-data";
export {
  DEFAULT_VEHICLE_COLOR,
  resolveVehicleShapeKey,
  vehicleColorRgb,
  VEHICLE_SHAPES,
  VEHICLE_TYPE_COLORS,
  type VehicleShape,
  type VehicleShapeKey,
} from "./plugins/vehicle-shape-catalog";
export {
  DEFAULT_FLIGHT_SIMULATOR_SETTINGS,
  FLIGHT_CAMERA_TOKEN,
  FLIGHT_MAX_SPEED_MAX,
  FLIGHT_MAX_SPEED_MIN,
  FLIGHT_MIN_AGL_MAX,
  FLIGHT_MIN_AGL_MIN,
  FLIGHT_SIMULATOR_PLUGIN_ID,
  FLIGHT_UNITS,
  LEVEL_CAMERA_PITCH,
  MAX_CAMERA_PITCH,
  MIN_CAMERA_PITCH,
  closeFlightSimulatorPanel,
  flightSimulatorPlugin,
  getFlightHudSnapshot,
  getFlightSimulatorSettings,
  getFlightSimulatorSnapshot,
  isFlightSimulatorPanelVisible,
  isFlying,
  normalizeFlightSimulatorSettings,
  openFlightSimulatorPanel,
  reattachFlightSimulator,
  restoreFlightSimulator,
  setFlightSimulatorSettings,
  startFlying,
  stopFlying,
  subscribeFlightHud,
  subscribeFlightSimulatorPanel,
  toggleFlying,
  type FlightHudState,
  type FlightSimulatorSettings,
  type FlightUnits,
} from "./plugins/flight-simulator";
export {
  DEFAULT_FLIGHT_MODEL,
  FEET_PER_METER,
  KNOTS_PER_MPS,
  MAX_FLIGHT_LATITUDE,
  NEUTRAL_CONTROLS,
  altitudeAboveGround,
  altitudeForZoom,
  approach,
  compassPoint,
  constrainToTerrain,
  normalizeHeading,
  normalizeLongitude,
  offsetPosition,
  stepFlight,
  turnRateDegPerSec,
  type AircraftState,
  type FlightControls,
  type FlightModelConfig,
  type FlightStepResult,
} from "./plugins/flight-simulator-physics";
