import type { Map as MapLibreMap } from "maplibre-gl";
import type { Layer } from "@deck.gl/core";
import type { GeoLibreAppAPI, GeoLibreDeckGL, GeoLibrePlugin } from "../types";
import { depthOcclusionParameters, ensureSharedDeckOverlay, setSharedDeckLayers } from "./shared-deck-overlay";
import { latLngToCell } from "h3-js";
import { clampEmissionsH3Resolution, EMISSIONS_H3_METRICS, EMISSIONS_H3_RAMPS, EMISSIONS_H3_RESOLUTION_MAX, EMISSIONS_H3_RESOLUTION_MIN, emissionsH3Color, type EmissionsH3Metric } from "./emissions-h3-ramps";
export { EMISSIONS_H3_RESOLUTION_MIN, EMISSIONS_H3_RESOLUTION_MAX } from "./emissions-h3-ramps";
import { energyWeightedDb } from "./emissions-h3-aggregation";
import { type EmissionsRow, readEmissionsRowsFromProvider, openEmissionsDatasetProvider, createNetworkKpiHttpSource, createNetworkKpiDirectorySource, fetchNetworkKpiManifestJson, readLocalNetworkKpiManifestJson, loadNetworkKpiGeometry, parseNetworkKpiManifest, type NetworkKpiDirectoryHandle } from "./emissions-h3-parquet-data";
import type { TestudoDatasetProvider } from "./testudo-dataset-provider";
import { listVehicleManifestScenarios, supportsLocalPackageFolders } from "./vehicle-playback-data";
import { registerDuckDbLayer, releaseDuckDbLayer } from "../shared/duckdb-layer-registry";
export const EMISSIONS_H3_PLUGIN_ID = "geolibre-emissions-h3";
export interface EmissionsH3Settings { manifestUrl:string|null; metric:EmissionsH3Metric; resolution:number; extruded:boolean; maxHeightM:number; opacity:number; interval:number; intervalPlaying:boolean; did:number|null; seeThroughBuildings:boolean; }
export const DEFAULT_EMISSIONS_H3_SETTINGS:EmissionsH3Settings = {manifestUrl:null,metric:"noise",resolution:8,extruded:true,maxHeightM:120,opacity:.85,interval:0,intervalPlaying:false,did:null,seeThroughBuildings:true};
export interface EmissionsH3Status { loading:boolean; error:string|null; intervals:number[]; did:number|null; scenarios:{index:number;id:string;label:string}[]; scenarioIndex:number; replications:{did:number;didname?:string}[]; localFolderName:string|null; hasResults:boolean; hasEmissions:boolean; }
const idle:EmissionsH3Status={loading:false,error:null,intervals:[],did:null,scenarios:[],scenarioIndex:0,replications:[],localFolderName:null,hasResults:false,hasEmissions:false}; let settings={...DEFAULT_EMISSIONS_H3_SETTINGS},status={...idle},visible=false,appRef:GeoLibreAppAPI|null=null,engine:EmissionsH3Engine|null=null,provider:TestudoDatasetProvider|null=null,loaded:{geometry:any;rows:EmissionsRow[]}|null=null,pending:{raw:unknown;url:string|null;directory:NetworkKpiDirectoryHandle|null}|null=null,token=0,timer:ReturnType<typeof setInterval>|null=null; const listeners=new Set<()=>void>(),panelListeners=new Set<()=>void>(); const notify=()=>listeners.forEach(f=>f()),notifyPanel=()=>panelListeners.forEach(f=>f());
function length(a:[number,number],b:[number,number]){const dx=(b[0]-a[0])*111320*Math.cos((a[1]+b[1])*Math.PI/360),dy=(b[1]-a[1])*110540;return Math.hypot(dx,dy);} function cellsForFeature(coords:number[][],resolution:number){const out=new Map<string,number>();for(let i=1;i<coords.length;i++){const a=coords[i-1] as [number,number],b=coords[i] as [number,number],d=length(a,b),n=Math.max(1,Math.ceil(d/30));for(let j=0;j<n;j++){const t=(j+.5)/n,c=latLngToCell(a[1]+(b[1]-a[1])*t,a[0]+(b[0]-a[0])*t,resolution);out.set(c,(out.get(c)||0)+d/n);}}return out;}
export function aggregateEmissionsH3(features:any[],rows:Map<number,EmissionsRow|EmissionsRow[]>,metric:EmissionsH3Metric,resolution:number){const bins=new Map<string,{length:number;energy:{db:number;length:number}[];value:number}>();for(const f of features){const matched=rows.get(Number(f.properties?.section_id??f.properties?.sectionId??f.properties?.oid));const rowList=matched?(Array.isArray(matched)?matched:[matched]):[];if(!rowList.length)continue;const line=f.geometry?.coordinates as number[][];if(!line)continue;const noise=rowList.reduce((sum,row)=>sum+row.noise.laeqSrcDb,0)/rowList.length;const values=metric==="noise"?[]:rowList.map(row=>Number(row[metric])).filter(Number.isFinite);if(metric!=="noise"&&!values.length)continue;const value=values.reduce((sum,current)=>sum+current,0);for(const [cell,len] of cellsForFeature(line,resolution)){const b=bins.get(cell)??{length:0,energy:[],value:0};b.length+=len;if(metric==="noise")b.energy.push({db:noise,length:len});else b.value+=value*len;bins.set(cell,b);}}return [...bins].map(([hex,b])=>({hex,value:metric==="noise"?energyWeightedDb(b.energy)??0:b.value/Math.max(b.length,1e-9)}));}
class EmissionsH3Engine { constructor(private map:MapLibreMap,private getDeck:()=>GeoLibreDeckGL|null){} render(){const deck=this.getDeck();if(!deck||!loaded){setSharedDeckLayers("emissions-h3",[]);return;}const byOid=new Map<number,EmissionsRow[]>();for(const row of loaded.rows){const group=byOid.get(row.oid)??[];group.push(row);byOid.set(row.oid,group);}
const data=aggregateEmissionsH3(loaded.geometry.sections.features,byOid,settings.metric,settings.resolution),ramp=EMISSIONS_H3_RAMPS[settings.metric];
const layer=new deck.geoLayers.H3HexagonLayer({id:"emissions-h3",data,getHexagon:(d:any)=>d.hex,getFillColor:(d:any)=>{const c=emissionsH3Color(d.value,settings.metric);return c?[...c,Math.round(settings.opacity*255)]:[0,0,0,0]},extruded:settings.extruded,getElevation:(d:any)=>settings.extruded?Math.min(settings.maxHeightM,Math.max(0,d.value/(ramp.stops.at(-1)||1)*settings.maxHeightM)):0,pickable:false,...depthOcclusionParameters(settings.seeThroughBuildings),updateTriggers:{getFillColor:[settings.metric,settings.opacity],getElevation:[settings.metric,settings.extruded,settings.maxHeightM]}}) as unknown as Layer;setSharedDeckLayers("emissions-h3",[layer]);}}
function attach(app:GeoLibreAppAPI){appRef=app;const map=app.getMap?.();if(!map)return;void ensureSharedDeckOverlay(app);void app.getDeckGL?.().then(deck=>{if(!engine)engine=new EmissionsH3Engine(map,()=>deck);engine.render();});}
export function openEmissionsH3Panel(app:GeoLibreAppAPI){visible=true;registerDuckDbLayer({pluginId:"emissions-h3",dispose:()=>{if(timer)clearInterval(timer);timer=null;if(provider)void provider.close();provider=null;loaded=null;pending=null;setSharedDeckLayers("emissions-h3",[]);}});attach(app);notifyPanel();} export function closeEmissionsH3Panel(){releaseDuckDbLayer("emissions-h3");if(timer)clearInterval(timer);timer=null;if(provider)void provider.close();provider=null;visible=false;engine=null;loaded=null;pending=null;setSharedDeckLayers("emissions-h3",[]);notifyPanel();notify();} export function reattachEmissionsH3(app:GeoLibreAppAPI){if(visible)attach(app);} export const isEmissionsH3PanelVisible=()=>visible; export const subscribeEmissionsH3Panel=(f:()=>void)=>{panelListeners.add(f);return()=>panelListeners.delete(f)}; export const getEmissionsH3Snapshot=()=>settings; export const subscribeEmissionsH3=(f:()=>void)=>{listeners.add(f);return()=>listeners.delete(f)}; export const getEmissionsH3Status=()=>status; export const subscribeEmissionsH3Status=subscribeEmissionsH3;
function readCurrent(){if(!provider)return;const t=++token;void readEmissionsRowsFromProvider(provider,settings.did??0,settings.interval).then(r=>{if(t!==token)return;settings={...settings,did:r.did,interval:r.intervals.includes(settings.interval)?settings.interval:(r.intervals.includes(0)?0:(r.intervals[0]??0))};loaded=loaded?{...loaded,rows:r.rows}:null;status={...status,intervals:r.intervals,did:r.did};engine?.render();notify();}).catch(e=>{if(t===token){status={...status,error:String(e)};notify();}});} export function setEmissionsH3Settings(n:Partial<EmissionsH3Settings>){settings={...settings,...n,resolution:clampEmissionsH3Resolution(n.resolution??settings.resolution)};if(n.interval!==undefined||n.did!==undefined)readCurrent();engine?.render();notify();} function syncTimer(){if(timer)clearInterval(timer);timer=settings.intervalPlaying?setInterval(()=>stepEmissionsH3Interval(1),1000):null;} export function toggleEmissionsH3IntervalPlaying(){settings={...settings,intervalPlaying:!settings.intervalPlaying};syncTimer();notify();} export function stepEmissionsH3Interval(direction:1|-1){const values=status.intervals.filter(v=>v!==0);if(values.length<2)return;const i=values.indexOf(settings.interval);setEmissionsH3Settings({interval:values[i<0?(direction===1?0:values.length-1):(i+direction+values.length)%values.length]});}
async function loadScenario(i:number,t:number){if(!pending)return;const m=parseNetworkKpiManifest(pending.raw,pending.url,i);const source=pending.directory?createNetworkKpiDirectorySource(pending.directory):createNetworkKpiHttpSource(pending.url!);const geometry=await loadNetworkKpiGeometry(source,m.geometry);if(t!==token)return;if(m.bounds)appRef?.fitBounds?.(m.bounds);if(provider)await provider.close();provider=await openEmissionsDatasetProvider(source,pending.raw);
// Noise/emissions come only from Aimsun Next's microscopic simulator — a
// meso/macroscopic export's MISECT will lack flow/speed/nstops entirely.
// Block here with an explicit message instead of silently rendering an
// all-floor-value (35 dB, zero CO2/NOx) grid that reads as real "quiet,
// clean" data rather than "no data for this package".
const r=await readEmissionsRowsFromProvider(provider,settings.did??0,settings.interval,m.package?.scenarios[i]?.scid);if(t!==token)return;if(!r.hasMicroscopicColumns){status={...status,loading:false,error:"This package has no microscopic simulation results (MISECT lacks flow/speed/stop data). Noise and emissions can only be computed from an Aimsun Next microscopic run."};notify();return;}settings={...settings,manifestUrl:pending.url,did:r.did,interval:r.intervals.includes(settings.interval)?settings.interval:(r.intervals.includes(0)?0:(r.intervals[0]??0))};loaded={geometry,rows:r.rows};status={...status,loading:false,intervals:r.intervals,did:r.did,hasResults:true,hasEmissions:r.hasEmissions,scenarios:listVehicleManifestScenarios(pending.raw),scenarioIndex:i,replications:m.package?.scenarios[i]?.replications??[],localFolderName:pending.directory?.name??null};engine?.render();notify();}
export async function setEmissionsH3ManifestUrl(url:string){const t=++token;status={...status,loading:true,error:null};notify();try{const raw=await fetchNetworkKpiManifestJson(url);pending={raw,url,directory:null};await loadScenario(0,t);}catch(e){status={...status,loading:false,error:String(e)};notify();}} export async function loadLocalEmissionsH3Folder(){const t=++token;if(!supportsLocalPackageFolders()){status={...status,error:"Local folders are not supported in this browser."};notify();return;}status={...status,loading:true,error:null};notify();try{const root=await(window as any).showDirectoryPicker() as NetworkKpiDirectoryHandle;if(t!==token)return;const raw=await readLocalNetworkKpiManifestJson(root);if(t!==token)return;pending={raw,url:null,directory:root};await loadScenario(0,t);}catch(e){if(t!==token)return;const cancelled=e instanceof Error&&e.name==="AbortError";status={...status,loading:false,error:cancelled?null:String(e)};notify();}}
export async function setEmissionsH3Scenario(i:number){if(!pending||i===status.scenarioIndex)return;const t=++token;status={...status,loading:true,error:null};notify();try{await loadScenario(i,t);}catch(e){if(t===token){status={...status,loading:false,error:String(e)};notify();}}}
export const maplibreEmissionsH3Plugin:GeoLibrePlugin={id:EMISSIONS_H3_PLUGIN_ID,name:"Emissions H3",version:"1.0.0",activeByDefault:false,activate:openEmissionsH3Panel,deactivate:closeEmissionsH3Panel,getProjectState:()=>visible?{open:true,...settings}:undefined,applyProjectState:(app,state)=>{if((state as any)?.open)openEmissionsH3Panel(app)}};
