// @ts-nocheck
import type { Map as MapLibreMap, MapMouseEvent } from "maplibre-gl";
import type { GeoLibreAppAPI, GeoLibrePlugin } from "../types";
import { createHttpPackageSource, supportsLocalPackageFolders, type VehicleDirectoryHandle } from "./vehicle-playback-data";
import { fetchNetworkKpiManifestJson } from "./network-kpi-data";
import { depthOcclusionParameters, ensureSharedDeckOverlay, setSharedDeckLayers } from "./shared-deck-overlay";
import { canLoadLocalPathAnalysisPackage, createPathAnalysisDirectorySource, loadPathAnalysis, parsePathAnalysisManifest, readLocalPathAnalysisManifestJson, type PathAnalysisData, type PathMatch, type PathRule } from "./path-analysis-data";
import { pathColorRgb, pathElevation, type PathMetric } from "./path-analysis-ramps";
import { bufferLineToRing } from "./network-kpi-geometry";
import { metersLineWidthExpression, sectionWidthMetersExpression } from "./maplibre-vehicle-playback";
import { registerDuckDbLayer, releaseDuckDbLayer } from "../shared/duckdb-layer-registry";
export const PATH_ANALYSIS_PLUGIN_ID="geolibre-path-analysis";
const SECTION_SOURCE="geolibre-path-analysis-sections",PATH_SOURCE="geolibre-path-analysis-paths",LABEL_SOURCE="geolibre-path-analysis-labels";
const PATH_RIBBON_WIDTH_M=12;
let loadToken=0;
export interface PathAnalysisSettings{manifestUrl:string|null;rule:PathRule;metric:PathMetric;extruded:boolean;maxHeightM:number;seeThroughBuildings:boolean}
export interface PathAnalysisSnapshot{settings:PathAnalysisSettings;loading:boolean;error:string|null;summary:Record<string,unknown>|null;selectedSections:number[];selectedSection:number|null;matches:PathMatch[]}
let snapshot:PathAnalysisSnapshot={settings:{manifestUrl:null,rule:"or",metric:"percentage",extruded:false,maxHeightM:20,seeThroughBuildings:true},loading:false,error:null,summary:null,selectedSections:[],selectedSection:null,matches:[]};let visible=false;let engine:PathAnalysisEngine|null=null;let appRef:GeoLibreAppAPI|null=null;const listeners=new Set<()=>void>(),panelListeners=new Set<()=>void>();const notify=()=>listeners.forEach(f=>f());
export const getPathAnalysisSnapshot=()=>snapshot;export const subscribePathAnalysis=(f:()=>void)=>(listeners.add(f),()=>listeners.delete(f));export const isPathAnalysisPanelVisible=()=>visible;export const subscribePathAnalysisPanel=(f:()=>void)=>(panelListeners.add(f),()=>panelListeners.delete(f));
function fitPathAnalysisBounds(bounds:[number,number,number,number]|null){if(bounds)appRef?.fitBounds?.(bounds)}
export function openPathAnalysisPanel(app:GeoLibreAppAPI){appRef=app;visible=true;registerDuckDbLayer({pluginId:"path-analysis",dispose:()=>{engine?.disposeData()}});panelListeners.forEach(f=>f());if(!engine){const map=app.getMap?.();if(map)engine=new PathAnalysisEngine(app,map)}}
// Disposes the engine's current PathAnalysisData (conn.close()/db.terminate()/
// worker.terminate() in path-analysis-data.ts) so closing the panel actually
// releases the DuckDB instance instead of leaking it. `engine.disposeData()`
// nulls out its own `data` field after closing, so a close-then-immediate-
// reload race (setData() firing right after) never double-closes: setData()'s
// own `this.data?.close()` sees the already-nulled field and no-ops.
export function closePathAnalysisPanel(){visible=false;releaseDuckDbLayer("path-analysis");engine?.disposeData();panelListeners.forEach(f=>f())}
export async function setPathAnalysisManifestUrl(url:string){const token=++loadToken;snapshot={...snapshot,settings:{...snapshot.settings,manifestUrl:url},loading:true,error:null};notify();try{const p=parsePathAnalysisManifest(await fetchNetworkKpiManifestJson(url),url);if(token!==loadToken)return;if(!p.available)throw new Error(p.unavailableReason??"Path data is unavailable in this package.");const d=await loadPathAnalysis(createHttpPackageSource(url),p);if(token!==loadToken)return;engine?.setData(d);fitPathAnalysisBounds(p.bounds);snapshot={...snapshot,loading:false,summary:d.summary,selectedSections:[],selectedSection:null,matches:[]}}catch(e){if(token!==loadToken)return;snapshot={...snapshot,loading:false,error:e instanceof Error?e.message:String(e)};notify()}notify()}
export async function loadLocalPathAnalysisFolder(){const token=++loadToken;if(!supportsLocalPackageFolders()){snapshot={...snapshot,error:"Local folders are not supported in this browser."};notify();return}snapshot={...snapshot,loading:true,error:null};notify();try{const root=await(window as any).showDirectoryPicker() as VehicleDirectoryHandle;if(token!==loadToken)return;const p=parsePathAnalysisManifest(await readLocalPathAnalysisManifestJson(root),null);if(token!==loadToken)return;const d=await loadPathAnalysis(createPathAnalysisDirectorySource(root),p);if(token!==loadToken)return;engine?.setData(d);fitPathAnalysisBounds(p.bounds);snapshot={...snapshot,loading:false,summary:d.summary,settings:{...snapshot.settings,manifestUrl:null}}}catch(e){if(token!==loadToken)return;snapshot={...snapshot,loading:false,error:(e as Error).name!=="AbortError"?(e instanceof Error?e.message:String(e)):null};notify()}}
export{canLoadLocalPathAnalysisPackage};export function reattachPathAnalysis(app:GeoLibreAppAPI){if(visible&&!engine){const map=app.getMap?.();if(map)engine=new PathAnalysisEngine(app,map)}}export function setPathAnalysisSettings(p:Partial<PathAnalysisSettings>){snapshot={...snapshot,settings:{...snapshot.settings,...p}};void engine?.refresh();notify()}export function clearPathAnalysisSelection(){void engine?.clearSelection()}
// Per-chip removal for the multi-select list, distinct from clearSelection()'s
// full reset — drops just the one id and re-runs the OR/AND query on what's left.
export function removePathAnalysisSection(id:number){snapshot={...snapshot,selectedSections:snapshot.selectedSections.filter(x=>x!==id),selectedSection:null};void engine?.refresh()}
class PathAnalysisEngine{private data:PathAnalysisData|null=null;private bound=false;private selectionToken=0;constructor(private app:GeoLibreAppAPI,private map:MapLibreMap){}
// Close and null out whatever data this engine currently holds. Idempotent —
// safe to call from closePathAnalysisPanel() even when setData() has already
// run (or never ran), since `this.data` is null in both those cases.
disposeData(){this.data?.close();this.data=null}
setData(d:PathAnalysisData){this.data?.close();this.data=d;const s=d.geometry.sections;const sectionSource=this.map.getSource(SECTION_SOURCE) as any;if(sectionSource)sectionSource.setData(s as any);else this.map.addSource(SECTION_SOURCE,{type:"geojson",data:s as any});snapshot={...snapshot,selectedSections:[],selectedSection:null,matches:[]};void this.render();notify();if(!this.map.getLayer(SECTION_SOURCE))this.map.addLayer({id:SECTION_SOURCE,type:"line",source:SECTION_SOURCE,paint:{"line-color":"#9ca3af","line-width":metersLineWidthExpression(sectionWidthMetersExpression()) as never,"line-opacity":.6}});if(!this.bound){this.map.on("click",SECTION_SOURCE,(e)=>void this.select(e));this.bound=true}}private async select(e:MapMouseEvent){const id=Math.trunc(Number((e.features?.[0]?.properties as any)?.section_id??(e.features?.[0]?.properties as any)?.id));if(!Number.isFinite(id)||!this.data)return;const add=e.originalEvent.ctrlKey||e.originalEvent.shiftKey;const next=add?(snapshot.selectedSections.includes(id)?snapshot.selectedSections.filter(x=>x!==id):[...snapshot.selectedSections,id]):[id];snapshot={...snapshot,selectedSections:next,selectedSection:id};await this.refresh()}async refresh(){const token=++this.selectionToken;if(!this.data||!snapshot.selectedSections.length){if(token!==this.selectionToken)return;snapshot={...snapshot,matches:[]};await this.render();notify();return}const matches=await this.data.query(snapshot.selectedSections,snapshot.settings.rule);if(token!==this.selectionToken)return;snapshot={...snapshot,matches};await this.render();notify()}async clearSelection(){snapshot={...snapshot,selectedSections:[],selectedSection:null,matches:[]};await this.render();notify()}async render(){if(!this.data)return;const sections=new Map<number,any>();for(const f of (this.data.geometry.sections as any).features??[]){const p=f.properties??{},id=Number(p.section_id??p.id??p.ID);if(Number.isFinite(id))sections.set(id,f.geometry)}const matchList=snapshot.matches.slice(0,200);
// `sequence()` is async (a DuckDB query per route), so every route's section
// list must be awaited before its coordinates can be assembled — the previous
// `for...of this.data.sequence(...)` iterated the returned Promise itself,
// which isn't iterable and threw on every real selection.
const sequences=await Promise.all(matchList.map(m=>this.data!.sequence(m.route_id)));
const features:any[]=[],ribbonFeatures:any[]=[],labels:any[]=[];matchList.forEach((m,i)=>{const coords:any[]=[];for(const sid of sequences[i]){const g=sections.get(sid);if(g?.type==="LineString")coords.push(...(coords.length?g.coordinates.slice(1):g.coordinates));else if(g?.type==="MultiLineString")for(const line of g.coordinates)coords.push(...(coords.length?line.slice(1):line))}if(coords.length>1){const value=snapshot.settings.metric==="trips"?m.demand:m.percentage*100;const properties={value,demand:m.demand,percentage:m.percentage};features.push({type:"Feature",properties,geometry:{type:"LineString",coordinates:coords}});const ring=bufferLineToRing(coords as [number,number][],PATH_RIBBON_WIDTH_M);if(ring)ribbonFeatures.push({type:"Feature",properties,geometry:{type:"Polygon",coordinates:[ring]}});labels.push({type:"Feature",properties:{label:snapshot.settings.metric==="trips"?`${m.demand.toFixed(0)} trips`:`${(m.percentage*100).toFixed(1)}%`},geometry:{type:"Point",coordinates:coords[Math.floor(coords.length/2)]}})}});const set=(id:string,data:any)=>{const s=this.map.getSource(id) as any;if(s)s.setData(data);else this.map.addSource(id,{type:"geojson",data})};set(PATH_SOURCE,{type:"FeatureCollection",features});set(LABEL_SOURCE,{type:"FeatureCollection",features:labels});if(!this.map.getLayer(PATH_SOURCE))this.map.addLayer({id:PATH_SOURCE,type:"line",source:PATH_SOURCE,paint:{"line-color":["interpolate",["linear"],["get","value"],0,"#dbeafe",25,"#60a5fa",50,"#22c55e",75,"#f59e0b",100,"#dc2626"],"line-width":4}});if(!this.map.getLayer(LABEL_SOURCE))this.map.addLayer({id:LABEL_SOURCE,type:"symbol",source:LABEL_SOURCE,layout:{"text-field":["get","label"],"text-size":11,"text-allow-overlap":true},paint:{"text-color":"#172554","text-halo-color":"#fff","text-halo-width":1.5}});if(this.app.getDeckGL)void this.app.getDeckGL().then((deck:any)=>ensureSharedDeckOverlay(this.app).then(()=>setSharedDeckLayers("path-analysis",snapshot.settings.extruded?[new deck.layers.PolygonLayer({id:"geolibre-path-analysis-3d",data:ribbonFeatures,getPolygon:(d:any)=>d.geometry.coordinates[0],getFillColor:(d:any)=>[...pathColorRgb(d.properties.value,snapshot.settings.metric),220],getElevation:(d:any)=>snapshot.settings.extruded?pathElevation(d.properties.value,snapshot.settings.metric,snapshot.settings.maxHeightM):0,extruded:snapshot.settings.extruded,filled:true,stroked:false,elevationScale:1,pickable:false,...depthOcclusionParameters(snapshot.settings.seeThroughBuildings),updateTriggers:{getFillColor:[snapshot.settings.metric],getElevation:[snapshot.settings.metric,snapshot.settings.extruded,snapshot.settings.maxHeightM]}} as any)]:[])))}}
export const maplibrePathAnalysisPlugin:GeoLibrePlugin={id:PATH_ANALYSIS_PLUGIN_ID,name:"Path analysis",version:"2.0.0",activate:app=>{openPathAnalysisPanel(app);return true},deactivate:()=>{void engine?.clearSelection();closePathAnalysisPanel();engine=null},getProjectState:()=>snapshot.settings,applyProjectState:(_a,s)=>{snapshot={...snapshot,settings:{...snapshot.settings,...s as any}};return true}};
